import { useState} from "react";
import Head from "next/head";
import styles from "../../styles/Home.module.css";

const defaultEndPoint = `https://api.themoviedb.org/3/trending/all/day?api_key=${process.env.NEXT_PUBLIC_SYSTEM_ID}`;

export async function getServerSideProps() {
  const res = await fetch(defaultEndPoint);
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
}
export default function Treading({ data }) {
  console.log(data)
  const { info, results: defaultResults = [] } = data;
  const [results, updateResults] = useState(defaultResults);
  


  

  return (
    <div className={styles.container}>
      <Head>
        <title> Movies From TMDB </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Movies From TMDB </h1>

        <p className={styles.description}>
           <code className={styles.code}></code>
        </p>

        <ul className={styles.grid}>
          {results.map((result) => {
            const { id,release_date, title, poster_path,vote_average } = result;
            const image = `https://image.tmdb.org/t/p/w200/${poster_path}`;

            return (
              <li key={id} className={styles.card}>
                <a >
                  <img src={image} alt={title} />
                  <p>{title}</p>
                  <h1>{release_date}</h1>
                  <h2>{vote_average}</h2>
                </a>
              </li>
            );
          })}
        </ul>
        
      </main>

     
    </div>
  );
}
